### ISSUE TITLE
https://skatelescope.org/ska-telescope not found.

### ISSUE THREAD

**Issue by NicholasRees** [ska-telescope/developer.skatelescope.org#20]
The list of projects (https://github.com/ska-telescope/developer.skatelescope.org/blob/master/src/projects/list.rst) has a link to https://skatelescope.org/ska-telescope which is meant to link to Github, I think. At the moment it doesn't and ends up with a file not found error at https://www.skatelescope.org

**Comment by flyingfrog81** [comment]
Fixed in https://github.com/ska-telescope/developer.skatelescope.org/commit/bbedf05968273afe75c0f63cc0e5c11f3377378a
