### ISSUE TITLE
broken download URL for base vbox image

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/developer.skatelescope.org#22]
The download link provided in tango-devenv-setup.rst for the ubuntu machine points to a dead link
@Matteo04052017 can you please replace it with a working one?

**Comment by Matteo04052017** [comment]
they keep changing it... Perhaps we need to download an image and put in our servers... any idea of where?

**Comment by bartashevich** [comment]
We could put it in nexus, I can create RAW repo for things like that

**Comment by flyingfrog81** [comment]
approved
